import React, { createContext, useContext, useState, useMemo } from 'react';
import type { Language, FontSize } from '../types';

// 1. TRANSLATION STRINGS
const translations = {
  en: {
    title: "Facial Time Machine",
    subtitle: "Travel through time, change your age, or even your career!",
    startOver: "Start Over",
    generateImage: "Generate Image",
    footer: "Powered by Gemini. Images are generated by AI and are for entertainment purposes only.",
    errorInvalidImage: "Please select a valid image file (PNG, JPG, etc.).",
    errorSelectImage: "Please select an image first.",
    errorTransformation: "An unknown error occurred during image transformation.",
    uploadTitle: "Upload Your Image",
    uploadSubtitle: "Drag & drop or click to select a file",
    uploadRecommended: "(PNG, JPG, WEBP recommended)",
    selectImage: "Select Image",
    or: "or",
    useCamera: "Use Camera",
    original: "Original",
    generated: "Generated",
    generating: "Generating...",
    awaitingGeneration: "Awaiting Generation",
    saveImage: "Save Image",
    saveAsPNG: "Save as PNG",
    saveAsJPG: "Save as JPG",
    share: "Share",
    shareTitle: "My Time Machine Image!",
    shareText: "Check out this image I created with the Facial Time Machine.",
    shareError: "Sharing failed or is not supported.",
    cameraTitle: "Camera",
    cameraError: "Could not access camera. Please ensure you have granted permission.",
    takePhoto: "Take Photo",
    cancel: "Cancel",
    targetAge: "Target Age",
    professionLabel: "Profession (Optional)",
    professionPlaceholder: "e.g., Doctor, Astronaut...",
    professionNone: "None",
    searchByVoice: "Search by voice",
    setBackgroundByVoice: "Set background by voice",
    speechRecognitionNotSupported: "Speech recognition is not supported in this browser.",
    advancedSettings: "Advanced Settings",
    backgroundLabel: "Custom Background (Optional)",
    backgroundPlaceholder: "e.g., on a beach, in a futuristic city...",
    settingsTitle: "Settings",
    language: "Language",
    fontSize: "Font Size",
    fontSizeNormal: "Normal",
    fontSizeLarge: "Large",
  },
  hi: {
    title: "फेशियल टाइम मशीन",
    subtitle: "समय में यात्रा करें, अपनी उम्र बदलें, या अपना करियर भी!",
    startOver: "फिर से शुरू करें",
    generateImage: "छवि बनाएं",
    footer: "जेमिनी द्वारा संचालित। छवियां एआई द्वारा उत्पन्न की जाती हैं और केवल मनोरंजन प्रयोजनों के लिए हैं।",
    errorInvalidImage: "कृपया एक वैध छवि फ़ाइल (PNG, JPG, आदि) चुनें।",
    errorSelectImage: "कृपया पहले एक छवि चुनें।",
    errorTransformation: "छवि परिवर्तन के दौरान एक अज्ञात त्रुटि हुई।",
    uploadTitle: "अपनी छवि अपलोड करें",
    uploadSubtitle: "फ़ाइल चुनने के लिए खींचें और छोड़ें या क्लिक करें",
    uploadRecommended: "(PNG, JPG, WEBP अनुशंसित)",
    selectImage: "छवि चुनें",
    or: "या",
    useCamera: "कैमरा का उपयोग करें",
    original: "मूल",
    generated: "उत्पन्न",
    generating: "बनाया जा रहा है...",
    awaitingGeneration: "उत्पन्न होने की प्रतीक्षा में",
    saveImage: "छवि सहेजें",
    saveAsPNG: "PNG के रूप में सहेजें",
    saveAsJPG: "JPG के रूप में सहेजें",
    share: "साझा करें",
    shareTitle: "मेरी टाइम मशीन छवि!",
    shareText: "फेशियल टाइम मशीन के साथ बनाई गई इस छवि को देखें।",
    shareError: "साझा करना विफल रहा या समर्थित नहीं है।",
    cameraTitle: "कैमरा",
    cameraError: "कैमरा तक नहीं पहुंच सका। कृपया सुनिश्चित करें कि आपने अनुमति दी है।",
    takePhoto: "फोटो लें",
    cancel: "रद्द करें",
    targetAge: "लक्ष्य आयु",
    professionLabel: "पेशा (वैकल्पिक)",
    professionPlaceholder: "उदा., डॉक्टर, अंतरिक्ष यात्री...",
    professionNone: "कोई नहीं",
    searchByVoice: "आवाज से खोजें",
    setBackgroundByVoice: "आवाज से पृष्ठभूमि सेट करें",
    speechRecognitionNotSupported: "इस ब्राउज़र में वाक् पहचान समर्थित नहीं है।",
    advancedSettings: "उन्नत सेटिंग्स",
    backgroundLabel: "कस्टम पृष्ठभूमि (वैकल्पिक)",
    backgroundPlaceholder: "उदा., समुद्र तट पर, भविष्य के शहर में...",
    settingsTitle: "सेटिंग्स",
    language: "भाषा",
    fontSize: "अक्षर आकार",
    fontSizeNormal: "सामान्य",
    fontSizeLarge: "बड़ा",
  },
  mr: {
    title: "फेशियल टाइम मशीन",
    subtitle: "वेळेत प्रवास करा, आपले वय बदला, किंवा आपले करिअर बदला!",
    startOver: "पुन्हा सुरू करा",
    generateImage: "प्रतिमा तयार करा",
    footer: "जेमिनी द्वारा समर्थित. प्रतिमा एआयद्वारे तयार केल्या आहेत आणि केवळ मनोरंजनासाठी आहेत.",
    errorInvalidImage: "कृपया एक वैध प्रतिमा फाइल (PNG, JPG, इ.) निवडा.",
    errorSelectImage: "कृपया प्रथम एक प्रतिमा निवडा.",
    errorTransformation: "प्रतिमा परिवर्तनादरम्यान अज्ञात त्रुटी आली.",
    uploadTitle: "तुमची प्रतिमा अपलोड करा",
    uploadSubtitle: "फाइल निवडण्यासाठी ड्रॅग आणि ड्रॉप करा किंवा क्लिक करा",
    uploadRecommended: "(PNG, JPG, WEBP शिफारस केलेले)",
    selectImage: "प्रतिमा निवडा",
    or: "किंवा",
    useCamera: "कॅमेरा वापरा",
    original: "मूळ",
    generated: "तयार केलेली",
    generating: "तयार होत आहे...",
    awaitingGeneration: "निर्मितीची प्रतीक्षा आहे",
    saveImage: "प्रतिमा जतन करा",
    saveAsPNG: "PNG म्हणून जतन करा",
    saveAsJPG: "JPG म्हणून जतन करा",
    share: "शेअर करा",
    shareTitle: "माझी टाइम मशीन प्रतिमा!",
    shareText: "मी फेशियल टाइम मशीनसह तयार केलेली ही प्रतिमा पहा.",
    shareError: "शेअरिंग अयशस्वी झाले किंवा समर्थित नाही.",
    cameraTitle: "कॅमेरा",
    cameraError: "कॅमेरामध्ये प्रवेश करू शकलो नाही. कृपया खात्री करा की आपण परवानगी दिली आहे.",
    takePhoto: "फोटो घ्या",
    cancel: "रद्द करा",
    targetAge: "लक्ष्य वय",
    professionLabel: "व्यवसाय (पर्यायी)",
    professionPlaceholder: "उदा., डॉक्टर, अंतराळवीर...",
    professionNone: "काहीही नाही",
    searchByVoice: "आवाजाने शोधा",
    setBackgroundByVoice: "आवाजाने पार्श्वभूमी सेट करा",
    speechRecognitionNotSupported: "या ब्राउझरमध्ये स्पीच रेकग्निशन समर्थित नाही.",
    advancedSettings: "प्रगत सेटिंग्ज",
    backgroundLabel: "सानुकूल पार्श्वभूमी (पर्यायी)",
    backgroundPlaceholder: "उदा., समुद्रकिनाऱ्यावर, भविष्यातील शहरात...",
    settingsTitle: "सेटिंग्ज",
    language: "भाषा",
    fontSize: "अक्षर आकार",
    fontSizeNormal: "सामान्य",
    fontSizeLarge: "मोठा",
  }
};


// 2. CONTEXT DEFINITION
interface SettingsContextType {
    language: Language;
    setLanguage: (language: Language) => void;
    fontSize: FontSize;
    setFontSize: (size: FontSize) => void;
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);


// 3. PROVIDER COMPONENT
export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('en');
    const [fontSize, setFontSize] = useState<FontSize>('normal');

    const value = useMemo(() => ({
        language,
        setLanguage,
        fontSize,
        setFontSize
    }), [language, fontSize]);

    return (
        <SettingsContext.Provider value={value}>
            {children}
        </SettingsContext.Provider>
    );
};

// 4. HOOK for settings
export const useSettings = (): SettingsContextType => {
    const context = useContext(SettingsContext);
    if (context === undefined) {
        throw new Error('useSettings must be used within a SettingsProvider');
    }
    return context;
};

// 5. HOOK for translations
type TranslationKey = keyof typeof translations['en'];

export const useTranslations = () => {
    const { language } = useSettings();

    const t = (key: TranslationKey): string => {
        return translations[language][key] || translations['en'][key];
    };
    
    return t;
};